import mediapipe as mp

class body_landmarker_results():
    def __init__(self): ...

    def createLandMarker(self):
        def update_result(result: mp.tasks.vision.PoseLandmarkerResult, output_image: mp.Image, timestamp_ms: int): ...
        ...
    
    def detect(self, frame): ...
    def close(self): ...